apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: nginx
      image: nginx
    - name: c2
      image: busybox
      command: ['sh', '-c', 'echo hello k8s!!! && sleep 3600']
